#### # 1. What is a Python library? Why ^o we use Python libraries?

<pre>A Python library is a collection of functions and modules that extend the capabilities of Python. These libraries provide reusable code that developers can use to perform various tasks without having to write the code from scratch. Libraries in Python can be either built-in (part of the Python standard library) or external (developed by third parties and made available for use).

Examples of built-in Python libraries include os, sys, and math, which provide functionalities for interacting with the operating system, accessing system-specific parameters and functions, and mathematical operations, respectively.

External Python libraries are vast and cover a wide range of domains such as data analysis, machine learning, web development, scientific computing, and more. Some popular external libraries include NumPy, Pandas, Matplotlib, TensorFlow, Flask, and Django.

Why do we use Python libraries?

Python libraries are used for several reasons:

Code Reusability: Libraries provide pre-written code that can be reused across different projects, saving time and effort by avoiding the need to reinvent the wheel.

Increased Productivity: By leveraging existing libraries, developers can accomplish complex tasks more efficiently and with fewer lines of code, leading to increased productivity.

Domain-specific Functionality: Python libraries are often tailored to specific domains or tasks, providing specialized functionalities and tools that are not available in the standard Python library.

Performance Optimization: Many Python libraries are optimized for performance, often using underlying C or Cython implementations, which can significantly improve the execution speed of computations and operations.

Community Support: Popular Python libraries have large communities of users and contributors who provide support, documentation, tutorials, and frequently update the libraries with new features and bug fixes.</pre>

#### 2. What is the difference between Numpy array and List?

<pre>Underlying Implementation:

NumPy arrays are homogeneous data structures, meaning that all elements in the array must be of the same data type. This allows NumPy to store data more efficiently in memory compared to Python lists.
Python lists, on the other hand, are heterogeneous data structures, meaning that they can contain elements of different data types.
Memory Efficiency:

NumPy arrays are stored as contiguous blocks of memory, allowing for efficient access and manipulation of data. This makes NumPy arrays more memory efficient compared to Python lists, especially when dealing with large datasets.
Python lists are implemented as dynamic arrays, which means that each element is stored in a separate block of memory with additional overhead for storing metadata about the list.
Functionality:

NumPy arrays provide a wide range of mathematical operations and functions for numerical computing, such as element-wise operations, linear algebra, statistical functions, and Fourier transforms.
Python lists offer basic operations such as indexing, slicing, appending, and concatenating. While Python lists can be used for a variety of tasks, they lack the extensive mathematical and numerical computing capabilities of NumPy arrays.
Performance:

NumPy operations are implemented in highly optimized C code, which makes them much faster compared to equivalent operations performed on Python lists using native Python code. This performance advantage is particularly significant when working with large datasets and performing complex numerical computations.
Python lists are generally slower for numerical computations, especially when performing operations on large datasets, due to the overhead of dynamic memory allocation and the lack of optimization for numerical computations.</pre>

#### 3. Find the shape, size and dimension of the following array?
<pre>[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]</pre>

In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

In [6]:
print('shape of array',arr.shape)
print('size of array',arr.size)
print('Dimention of array',arr.ndim)

shape of array (3, 4)
size of array 12
Dimention of array 2


#### 4. Write python code to access the first row of the following array?
<pre>[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]</pre>

In [ ]:
arr = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]

In [8]:
# to use first row of numpy array we can use slicing
arr[0]

array([1, 2, 3, 4])

In [11]:
# to use first row of numpy array we can use ndim slicing
arr[arr.ndim - arr.ndim]

array([1, 2, 3, 4])

In [18]:
# to use first row of numpy array we can use shape slicing
arr[arr.shape[0]+1-arr.shape[1]]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?
<pre>[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]</pre>

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

In [27]:
# to access element at specific location rows,columns we can use matrix slicing 
arr[2][3]

12

#### 6. Write code to extract all odd-indexed elements from the given numpy array?
<pre>[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]</pre>

In [60]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

In [59]:
# static way to extract odd indexed values
arr[0][1::2] , arr[1][1::2], arr[2][1::2]

(array([2, 4]), array([6, 8]), array([10, 12]))

In [61]:
# dynamic way to extract odd indexed values
arr = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

odd_indexed_arrays = [subarr[1::2] for subarr in arr]

print(odd_indexed_arrays)


[[2, 4], [6, 8], [10, 12]]


In [63]:
for o,i in enumerate(arr):
    print(o,i)

0 [1, 2, 3, 4]
1 [5, 6, 7, 8]
2 [9, 10, 11, 12]


#### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [89]:
import random

arr = np.array([[random.randint(0,1),random.randint(0,1),random.randint(0,1)],
                [random.randint(0,1),random.randint(0,1),random.randint(0,1)],
                [random.randint(0,1),random.randint(0,1),random.randint(0,1)]])
arr

array([[0, 1, 0],
       [1, 0, 1],
       [1, 0, 0]])

In [94]:
arr = np.array([[random.randint(0,1),random.randint(0,1),random.randint(0,1)],
                [random.randint(0,1),random.randint(0,1),random.randint(0,1)],
                [random.randint(0,1),random.randint(0,1),random.randint(0,1)]])/1.0
arr

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])

In [92]:
values = np.linspace(0, 1, 9).reshape(3, 3)
print(values)

[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


#### 8. Describe the difference between np.random.rand and np.random.randn?

In [95]:
np.random.rand(3,2)

array([[0.22547577, 0.18178797],
       [0.85314216, 0.03489657],
       [0.22026372, 0.43885421]])

<pre>
rand(d0, d1, ..., dn)

Random values in a given shape.

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

Parameters
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.

Returns
out : ndarray, shape (d0, d1, ..., dn)
    Random values.</pre>

In [96]:
np.random.randn()

1.6443967037719738

<pre>randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

If positive int_like arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate "normal" (Gaussian) distribution of mean 0 and variance 1. A single float randomly sampled from the distribution is returned if no argument is provided.

Parameters
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.

Returns
Z : ndarray or float
    A (d0, d1, ..., dn)-shaped array of floating-point samples from the standard normal distribution, or a single such float if no parameters were supplied.</pre>

#### 9. Write code to increase the dimension of the following array?
<pre>
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]</pre>

In [100]:
arr = np.array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]])
# Increase the dimension of the array
expanded_arr = np.expand_dims(arr, axis=0)

print('Original dimention',arr.ndim)
print('Expanded dimention',expanded_arr.ndim)

Original dimention 2
Expanded dimention 3


#### 10. How to transpose the following array in NumPy?
<pre>[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]</pre>

In [ ]:
arr = np.array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]])

#### 11. Consider the following matrix:
<pre>Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python:
1 Index wiLe multiplication
2 Matix multiplicatio'
3 Add both the maticK
4 Subtact matix B om 
5 Divide Matix B by A</pre>

In [2]:

# Define matrices A2 and B2
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Add both matrices
addition_result = A2 + B2
print("Addition result:")
print(addition_result)

# Subtract matrix B from matrix A
subtraction_result = A2 - B2
print("\nSubtraction result (A2 - B2):")
print(subtraction_result)

# Matrix multiplication
multiplication_result = np.dot(A2, B2.T)  # Assuming you want to perform matrix multiplication
print("\nMatrix multiplication result:")
print(multiplication_result)

# Element-wise division of matrix B by matrix A
division_result = np.divide(B2, A2)
print("\nDivision result (B2 / A2):")
print(division_result)


Addition result:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction result (A2 - B2):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix multiplication result:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Division result (B2 / A2):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 12. Which function in Numpy can be used to swap the byte order of an array?

In [ ]:
np.ndarray.byteswap(). #It swaps the bytes of the array element in place.

In [3]:
# import numpy as np

# Create an array with dtype int16 (2-byte integers)
arr = np.array([1, 256], dtype=np.int16)
print("Original array:")
print(arr)

# Swap the byte order of the array
arr.byteswap(True)
print("\nArray after byte swapping:")
print(arr)


Original array:
[  1 256]

Array after byte swapping:
[256   1]


#### 13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function is used to compute the multiplicative inverse of a matrix. It is significant in linear algebra and is commonly used in various mathematical computations, including solving systems of linear equations and computing determinants.

In [4]:
# Create a 2x2 matrix
A = np.array([[2, 1], [1, 3]])
print("Original matrix:")
print(A)

# Compute the inverse of the matrix
A_inv = np.linalg.inv(A)
print("\nInverse of the matrix:")
print(A_inv)

Original matrix:
[[2 1]
 [1 3]]

Inverse of the matrix:
[[ 0.6 -0.2]
 [-0.2  0.4]]


#### 14. What does the np.reshape function do, and how is it used?

The np.reshape function is used to change the shape of an array without changing its data. It returns a new array with a modified shape. This function is useful for reorganizing data to fit different dimensional requirements.

In [5]:
# Create a 1D array from 0 to 11
arr = np.arange(12)
print("Original 1D array:")
print(arr)

# Reshape the array into a 3x4 matrix
reshaped_arr = np.reshape(arr, (3, 4))
print("\nReshaped 3x4 matrix:")
print(reshaped_arr)

Original 1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped 3x4 matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### What is broadcasting in NumPy?

Broadcasting is a mechanism in NumPy that allows arrays with different shapes to be combined in arithmetic operations. When performing operations on arrays with different shapes, NumPy automatically "broadcasts" the arrays to make their shapes compatible, effectively extending the smaller array to match the shape of the larger one. This allows element-wise operations to be performed between arrays of different shapes without explicitly reshaping them. Broadcasting is an essential feature in NumPy that simplifies many array computations and makes code more concise and readable.

In [6]:
# Create a 2x3 array
A = np.array([[1, 2, 3], [4, 5, 6]])
print("Array A:")
print(A)

# Add a scalar value to each element of the array using broadcasting
scalar = 10
result = A + scalar
print("\nResult of broadcasting scalar addition:")
print(result)

Array A:
[[1 2 3]
 [4 5 6]]

Result of broadcasting scalar addition:
[[11 12 13]
 [14 15 16]]
